version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 324153226791.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...      
      - echo customer name is $CustomerName
      - docker build -f dockerfile -t $CustomerName ./build
      - ls
      - docker tag $CustomerName:latest 324153226791.dkr.ecr.ap-south-1.amazonaws.com/poc:latest  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 324153226791.dkr.ecr.ap-south-1.amazonaws.com/poc:latest