apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fe-landing
  name: fe-landing
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-landing
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fe-landing
    spec:
      containers:
      - image: {{ .Values.frontendLandingDeploy.image }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.frontendLandingDeploy.name }}
        ports:
        - containerPort: {{ .Values.frontendLandingDeploy.containerPort }}
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30