apiVersion: v1
kind: Secret  # Create a secret
metadata:
  name: mysecret
  namespace: default     
type: Opaque
data:
  POSTGRES_DB: bXRhX2RhdGE=   #mta_data
  POSTGRES_USER: administrator   # Set Postgres Username
  POSTGRES_PASSWORD: admin123    # Set Postgres Password